# Copyright 2025 Pixagan Technologies
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Self Reflection agent

from laeyerz.utils.KeyManager import KeyManager

from laeyerz_nodes.llm.OpenAINode import OpenAINode as LLM
from laeyerz.flow import Flow

import simplejson as json

km = KeyManager('YOUR_API_KEY_PATH_HERE')

drafter = LLM("Drafter", config={"api_key": km["OPENAI_API_KEY"], "model":"gpt-5-mini"})

summarizer = LLM("Summarizer", config={"api_key": km["OPENAI_API_KEY"], "model":"gpt-5-mini"})

critic = LLM("Critic", config={"api_key": km["OPENAI_API_KEY"], "model":"gpt-5-mini"})

refiner = LLM("Refiner", config={"api_key": km["OPENAI_API_KEY"], "model":"gpt-5-mini"})


def Drafter(user_request, context):

    drafter_instructions = """Your role is of a content drafter. 
    You will be provided the user request, specifying what the user want you to draft.
    If you are provided CONTEXT, use the context to make your draft accurate.
    If you are given any additional writing style parameters like tone etc use them as well.
    If the user_request does not require context, you may create the response as you please.
    If the user request involves something that requires the user to provide context, then DO NOT SPECULATE, USE THE CONTEXT PROVIDED.
    IF NOT ENOUGH INFORMATION IS REQUIRED, USE A PLACEHOLDER IN THE RESPONSE INDICATING WHAT INFORMATION THE USER NEEDS TO FILL UP AND WHERE.
    CONTEXT
    Rules:
    - Do NOT invent facts not present in the context.
    - If required information is missing, leave placeholders instead using the format <PlaceHolder for ...>
    - Keep the draft realistic and concise.
    Respond purely with the Draft, do not add any additional text to your response.
    """

    print("Drafting the initial answer ...")

    messages = [
                {"role": "developer", "content": drafter_instructions},
                {"role": "user", "content": "The user request is: " + user_request},   
            ]

    if(context):
        messages.append({"role": "user", "content": "The context is: " + context})

    if(styling):
        messages.append({"role": "user", "content": "Other styling instructions is: " + styling})

    draft = drafter.call_llm(messages)
    draft = draft['message'].content

    return draft


def Summarizer(user_request, context):

    print("Critiquing the draft ...")

    summarizer_instructions = """
    Get the relevant keypoints and info from the user provided context into relevant points depending what information the user might require based on the user request.
    """

    messages= [
            {"role": "developer", "content": "Instructions : "+summarizer_instructions},
            {"role": "developer", "content": user_request},
            {"role": "developer", "content":context},
    ]

    
    summary = summarizer.call_llm(messages)
    summary = summary['message'].content
    
  
    print("****************")

    return summary
    


def Critic(user_request, draft, summary, keypoints):

    print("Critiquing the draft ...")

    critic_instruction = """
    You need to critique the draft generated by the user.You'll be given the users initial request.
    If the critique metrics are provided use them to critique the draft and make sure the user request meets the specified criterion.
    Also check for clarity, and brevity, highlight any redundencies and structural issues.
    If no critique is provided, then check purely for clarity, and brevity, highlight any redundencies and structural issues.
    You want the draft to be as clear, minimal and to the point as possible without leaving out any important points.
    If any corrections feel required, suggest them in the critique section of the response and flag refine to "true" else, if
    the draft is good based on the criterion above, flag refine to "false", dont suggest any corrections.
    Keep the critique text such that it can be parsed by a JSON parser, dont use character that mess with that.
    """

    response_format = """
    {
        "refine":"true",
        "critique":[<critique 1>, <critique 2>]
    }
    """

    messages= [
            {"role": "developer", "content": critic_instruction},
            {"role": "developer", "content": response_format},
            {"role": "user", "content": user_request},
            {"role": "user", "content": "Key Context Points: " + summary},
            {"role": "user", "content": draft}
    ]

    
    critique = critic.call_llm(messages)
    critique = critique['message'].content
    
    
    print("****************")

    return critique



def Refiner(user_request, draft, critique, summary):

        print("Refining the draft ...")

        refiner_instruction = """
        You are a draft refiner.
    Given the draft and its critique, make the required changes to the draft purely based on the suggestions provided as critique to make changes.
    Only make edits, do not make wholesale changes that completely change the original draft.
    DO NOT ADD OR MAKE UP ANY INFORMATION AS PART OF THE EDITS. IF THE CRITIQUE SUGGESTS A CHANGE AND YOU DONT HAVE ENOUGH INFO TO DO SO,
    AT THE MOST ADD A PLACE HOLDER IN THE FORMAT <PLACEHOLDER : SUGGEST USER ADDS POINT1>. 

    Edit the draft minimally and only where strictly required.

Rules:
1. Only implement the critique_points.
2. Do not introduce new requirements or sections.
3. Keep the length similar unless required.
4. Preserve correct parts.
"""

        messages = [
                {"role": "developer", "content": user_request},
                {"role": "user", "content": draft},
                {"role": "user", "content": "Key Context Points: " + summary},
                {"role": "user", "content": str(critique)}
        ]

        
        draft = refiner.call_llm(messages)
        draft = draft['message'].content

        return draft


def self_review_llm(user_request, context, criterion):

    max_iters =  3
    

    draft = Drafter(user_request, context)

    summary = Summarizer(user_request, context)


    print("------------------------------------------")
    print("Initial Draft:", draft)

    for i in range(max_iters):
        print(f"\n=== ITERATION {i+1} ===")


   

        critique = Critic(user_request, draft, summary, criterion)
        print("Iteration  " + str(i+1) + " ------" )
        print("critique : ", critique)

   

        critique = json.loads(critique, strict="False")

        if (critique["refine"] == "false" or critique["refine"] == False) or i >= max_iters:
            return draft
            break
       

      
        draft = Refiner(user_request, draft, json.dumps(critique), summary)

      
        print("****************")
        
    return draft




#Test case
#The query has an error in the user request by design, so LLM should flag it.
user_request = """Draft a reply to the mail for my accountant asking for info sales for Month Deb 2026."""
styling = str({"tone":"urgent"})
context = """3 transactions.
2 Sales of Dell Laptop for Rs 40000.
1 sales of Monitor for Rs 20000.
Details to follow in next email
"""

criterion = "Check for accuracy and keep it precise."

final_answer = self_review_llm(user_request, context, criterion)
print("--------------------------------")
print("\nFINAL ANSWER:\n", final_answer)